name: CSE Daily Report Download

# When to run
on:
  schedule:
    # Runs daily at 2 AM UTC (adjust time as needed)
    - cron: '0 2 * * *'
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    # Install dependencies
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    # Run the script
    - name: Download CSE Daily Report
      run: python cse_downloader.py
      
    # Upload downloaded files as artifacts
    - name: Upload PDF files
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cse-daily-reports-${{ github.run_number }}
        path: downloads/
        retention-days: 30
        
    # Commit and push files back to repo (optional)
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add downloads/ || true
        git commit -m "Add downloaded report $(date)" || exit 0
        git push || true
