name: CSE Daily Report Downloader

on:
  schedule:
    - cron: '30 14 * * *' # Runs every day at 8:00 PM Sri Lankan time (14:30 UTC)
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        CHROME_DRIVER_VERSION=$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -q -O chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver.zip
        sudo mv chromedriver /usr/local/bin/
        
    - name: Run script
      run: python cse_daily_downloader.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add downloads/
        git diff --staged --quiet || (git commit -m "Add latest CSE daily report" && git push)
